# Generated by Django 3.1.2 on 2020-10-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('qs_one', models.CharField(max_length=30)),
                ('qs_two', models.CharField(max_length=30)),
                ('qs_three', models.CharField(max_length=30)),
                ('qs_one_cnt', models.IntegerField(default=0)),
                ('qs_two_cnt', models.IntegerField(default=0)),
                ('qs_three_cnt', models.IntegerField(default=0)),
            ],
        ),
    ]
